name: CI-CD

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: [self-hosted, linux]

    env:
      RUNNER_TOOL_CACHE: $HOME/.toolcache

    steps:
    - uses: actions/checkout@v4

    - name: Ensure tool cache directory
      run: mkdir -p "$HOME/.toolcache"

    - name: Install .NET locally in $HOME
      run: |
        wget https://dot.net/v1/dotnet-install.sh -O dotnet-install.sh
        chmod +x dotnet-install.sh
        ./dotnet-install.sh --channel 8.0 --install-dir "$HOME/dotnet"
        echo "$HOME/dotnet" >> $GITHUB_PATH
        echo "DOTNET_ROOT=$HOME/dotnet" >> $GITHUB_ENV

    - name: Verify dotnet
      run: |
        dotnet --info

    - run: dotnet restore
      working-directory: DroneDeliveryApp
    - run: dotnet build
      working-directory: DroneDeliveryApp
    - run: dotnet test
      working-directory: DroneDeliveryApp
